name: dating_app_3
description: A new Flutter project.


publish_to:

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_riverpod: ^1.0.4
  http: ^0.13.4
  get: ^4.6.5
  shared_preferences: ^2.0.15
  share: ^2.0.4
  fluttertoast: ^8.0.8




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/

